//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: EboASR.ice
//  Source: EboASR.idsl
//
//******************************************************************
#ifndef ROBOCOMPEBOASR_ICE
#define ROBOCOMPEBOASR_ICE
module RoboCompEboASR
{
	interface EboASR
	{
		string listenandtranscript ();
	};
};

#endif
